services:

  api-banxico:
    build: ./banxico
    volumes:
      - ./banxico:/Banxico
      - ../Datos/Banxico:/Banxico/app/src/main/resources
  api-inegi:
    build: ./INEGI
    volumes:
      - ./INEGI:/INEGI
      - ../Datos/INEGI:/INEGI/data
    